DSN=DadosADV;Description=DADOSADV;UID=******;PWD=*******;APP=Microsoft Office;WSID=MCNOTE-0229;DATABASE=DadosADV;LANGUAGE=Português;Network=DBMSSOCN;QueryLog_On=Yes;StatsLog_On=Yes


SELECT A1_NOME,IMP.* 
FROM rel.MC_IMPAPRVCLI IMP
INNER JOIN SA1010 s ON s.A1_COD+s.A1_LOJA=IMP.CLIENTE
WHERE IMP.DATA > dateadd(MM,-1, getdate());

BEGIN TRANSACTION
	SELECT A1_NOME, IMP.*, A1_CGC 
		FROM rel.MC_IMPAPRVCLI AS IMP
		INNER JOIN dbo.SA1010 as S ON S.A1_COD+S.A1_LOJA = IMP.CLIENTE
		WHERE IMP.DATA > DATEADD(DD,-15, GETDATE()) 
		ORDER BY DATA DESC
;


BEGIN TRANSACTION
	SELECT A1_NOME, IMP.*, A1_CGC 
		FROM rel.MC_IMPAPRVCLI AS IMP
		INNER JOIN dbo.SA1010 AS S ON S.A1_COD+S.A1_LOJA = IMP.CLIENTE
		WHERE IMP.DATA > DATEADD(DD,-5, GETDATE())
;

SELECT A1_NOME, IMP.*, A1_CGC 
		FROM rel.MC_IMPAPRVCLI AS IMP
		INNER JOIN dbo.SA1010 as S ON S.A1_COD+S.A1_LOJA = IMP.CLIENTE
		WHERE IMP.APRV LIKE 'associado ao vendedor = %@%'
		;

SELECT A1_NOME, IMP.*, A1_CGC 
		FROM rel.MC_IMPAPRVCLI AS IMP
		INNER JOIN dbo.SA1010 as S ON S.A1_COD+S.A1_LOJA = IMP.CLIENTE
		WHERE IMP.STATUS = 'PENDENTE' AND A1_NOME LIKE 'SOLAR%'
		;